Refactor the patch and run Python scripts
oliverdunk/NertsPlus pull request #5
Opened 2022-05-05 14:47 UTC by AmusedNetwork

This commit refactors the patch.py script to be nicer to work on 😋

There are now command line arguments for patch.py:
 --run: "Run the patched Nerts executable"
    (Note: run.py still works as before)
 --nerts_path: "Path to the Nerts executable"
 --skip_download: "Skip downloading de4dot"
 --bin-dir: "Directory to store de4dot and temporary executables" (This is slightly broken, it only works with absolute paths)

I haven't tested this on Linux or MacOS yet (cc @oliverdunk).

Thanks

2022-05-14 16:22 UTC, oliverdunk requested changes
This seems like a huge win, thanks for making the Python a million times nicer. Appreciate it!

2022-05-14 16:22 UTC, oliverdunk commented on utils.py
> +    subprocess.call(command_list, cwd=cwd, shell=True)
Unfortunately I don't think this works as you want it to on Windows. Reading [this](https://stackoverflow.com/questions/20128114/pythons-subprocess-does-not-interpret-as-expected-on-cygwin/20137299#20137299), it seems like the arguments get ignored:

> If args is a sequence, the first item specifies the command string, and any additional items will be treated as additional arguments to the shell itself.

We may just want to join them together if that works on Windows? Or find a different solution.

2022-05-17 10:49 UTC, AmusedNetwork commented
Your changes broke the Windows version :-( - there is probably a better way to do this, but for now we can just check if the system is Darwin and do it your way, else do it the way that works on Windows.

2022-05-21 23:13 UTC, oliverdunk commented
Thanks for the Windows fix!

2022-05-21 23:13 UTC, merged